# Generated by Django 5.0.6 on 2024-06-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
    ]
