# Generated by Django 5.0.6 on 2024-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra'),
        ),
    ]
