# Generated by Django 5.0.6 on 2024-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='¿Es un servicio?'),
        ),
    ]
