# Generated by Django 5.0.6 on 2024-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_product_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='code_sale',
            field=models.CharField(default='spam', verbose_name='Codigo de venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(choices=[('create', 'Creado'), ('update', 'Actualizado'), ('delete', 'Eliminado')], max_length=10, verbose_name='Acción'),
        ),
    ]
